// ---------------------------------------------------------------------------
// Top Japanese vocabulary, ranked by spoken-language frequency.
//
// SOURCE (verifiable): Adsonant "1,000 Most Common Japanese Words" -- compiled
// from 2,068,294 Japanese movie subtitles (opus.nlpl.eu corpus). Provides a
// frequency-ranked list of the most common words in spoken Japanese.
//   https://adsonant.com/resources/japanese/1000-most-common-words/
//
// 862 unique lemmas (duplicate frequency rows for the same word+reading are
// collapsed to a single entry; 'rank' preserves the source ordering).
// Each entry matches the VocabItem shape plus an optional rank.
// ---------------------------------------------------------------------------

import type { VocabItem } from './japanese'

export const topVocabulary: VocabItem[] = [
  { id: 'v1', jp: 'する', reading: 'する', en: 'do', rank: 1 },
  { id: 'v2', jp: 'ない', reading: 'ない', en: 'not', rank: 2 },
  { id: 'v3', jp: 'こと', reading: 'こと', en: 'thing', rank: 3 },
  { id: 'v4', jp: 'いる', reading: 'いる', en: 'exist', rank: 4 },
  { id: 'v5', jp: 'どう', reading: 'どう', en: 'how', rank: 5 },
  { id: 'v6', jp: 'いい', reading: 'いい', en: 'good', rank: 6 },
  { id: 'v7', jp: 'そう', reading: 'そう', en: 'so', rank: 7 },
  { id: 'v8', jp: 'ある', reading: 'ある', en: 'have', rank: 8 },
  { id: 'v9', jp: 'くれる', reading: 'くれる', en: 'give', rank: 9 },
  { id: 'v10', jp: '事', reading: 'こと', en: 'matter', rank: 10 },
  { id: 'v11', jp: 'もう', reading: 'もう', en: 'already', rank: 11 },
  { id: 'v12', jp: '言う', reading: 'いう', en: 'say', rank: 12 },
  { id: 'v13', jp: '見る', reading: 'みる', en: 'see', rank: 13 },
  { id: 'v14', jp: 'よう', reading: 'よう', en: 'way', rank: 14 },
  { id: 'v15', jp: '今', reading: 'いま', en: 'now', rank: 15 },
  { id: 'v16', jp: '来る', reading: 'くる', en: 'come', rank: 16 },
  { id: 'v17', jp: 'やる', reading: 'やる', en: 'do', rank: 17 },
  { id: 'v18', jp: '人', reading: 'ひと', en: 'person', rank: 18 },
  { id: 'v19', jp: 'なる', reading: 'なる', en: 'become', rank: 19 },
  { id: 'v20', jp: '知る', reading: 'しる', en: 'know', rank: 20 },
  { id: 'v21', jp: '前', reading: 'まえ', en: 'before', rank: 21 },
  { id: 'v22', jp: '行く', reading: 'いく', en: 'go', rank: 22 },
  { id: 'v23', jp: 'ため', reading: 'ため', en: 'purpose', rank: 23 },
  { id: 'v24', jp: '必要', reading: 'ひつよう', en: 'necessary', rank: 24 },
  { id: 'v25', jp: 'いう', reading: 'いう', en: 'say', rank: 25 },
  { id: 'v26', jp: '気', reading: 'き', en: 'spirit', rank: 26 },
  { id: 'v27', jp: 'もの', reading: 'もの', en: 'thing', rank: 27 },
  { id: 'v28', jp: '話', reading: 'はなし', en: 'story', rank: 28 },
  { id: 'v29', jp: '大丈夫', reading: 'だいじょうぶ', en: 'okay', rank: 29 },
  { id: 'v30', jp: '思う', reading: 'おもう', en: 'think', rank: 30 },
  { id: 'v31', jp: '奴', reading: 'やつ', en: 'guy', rank: 31 },
  { id: 'v32', jp: '自分', reading: 'じぶん', en: 'oneself', rank: 32 },
  { id: 'v33', jp: '時', reading: 'とき', en: 'time', rank: 33 },
  { id: 'v34', jp: 'できる', reading: 'できる', en: 'can', rank: 34 },
  { id: 'v35', jp: '本当', reading: 'ほんとう', en: 'truth', rank: 35 },
  { id: 'v36', jp: '時間', reading: 'じかん', en: 'time', rank: 36 },
  { id: 'v37', jp: 'まだ', reading: 'まだ', en: 'yet', rank: 37 },
  { id: 'v38', jp: 'なぜ', reading: 'なぜ', en: 'why', rank: 38 },
  { id: 'v39', jp: 'くる', reading: 'くる', en: 'come', rank: 39 },
  { id: 'v40', jp: '聞く', reading: 'きく', en: 'hear', rank: 40 },
  { id: 'v41', jp: '分かる', reading: 'わかる', en: 'understand', rank: 41 },
  { id: 'v42', jp: '男', reading: 'おとこ', en: 'man', rank: 42 },
  { id: 'v43', jp: 'ちょっと', reading: 'ちょっと', en: 'a little', rank: 43 },
  { id: 'v44', jp: 'わかる', reading: 'わかる', en: 'understand', rank: 44 },
  { id: 'v45', jp: '持つ', reading: 'もつ', en: 'have', rank: 45 },
  { id: 'v46', jp: '一', reading: 'いち', en: 'one', rank: 46 },
  { id: 'v47', jp: '出る', reading: 'でる', en: 'exit', rank: 47 },
  { id: 'v48', jp: '仕事', reading: 'しごと', en: 'work', rank: 48 },
  { id: 'v49', jp: '年', reading: 'とし', en: 'year', rank: 49 },
  { id: 'v50', jp: '一緒', reading: 'いっしょ', en: 'together', rank: 50 },
  { id: 'v51', jp: '話す', reading: 'はなす', en: 'speak', rank: 51 },
  { id: 'v52', jp: '待つ', reading: 'まつ', en: 'wait', rank: 52 },
  { id: 'v53', jp: '中', reading: 'なか', en: 'inside', rank: 53 },
  { id: 'v54', jp: 'すぐ', reading: 'すぐ', en: 'immediately', rank: 54 },
  { id: 'v55', jp: '家', reading: 'いえ', en: 'house', rank: 55 },
  { id: 'v56', jp: '手', reading: 'て', en: 'hand', rank: 56 },
  { id: 'v57', jp: '違う', reading: 'ちがう', en: 'different', rank: 57 },
  { id: 'v58', jp: '電話', reading: 'でんわ', en: 'telephone', rank: 58 },
  { id: 'v59', jp: 'なさる', reading: 'なさる', en: 'do', rank: 59 },
  { id: 'v60', jp: 'みたい', reading: 'みたい', en: 'like', rank: 60 },
  { id: 'v61', jp: '無い', reading: 'ない', en: 'not exist', rank: 61 },
  { id: 'v62', jp: '死ぬ', reading: 'しぬ', en: 'die', rank: 62 },
  { id: 'v63', jp: '1', reading: '１', en: 'one', rank: 63 },
  { id: 'v64', jp: '父', reading: 'ちち', en: 'father', rank: 64 },
  { id: 'v65', jp: 'みんな', reading: 'みんな', en: 'everyone', rank: 65 },
  { id: 'v66', jp: '良い', reading: 'いい', en: 'good', rank: 66 },
  { id: 'v67', jp: '2', reading: '２', en: 'two', rank: 67 },
  { id: 'v68', jp: '見つける', reading: 'みつける', en: 'find', rank: 68 },
  { id: 'v69', jp: '度', reading: 'ど', en: 'degree', rank: 69 },
  { id: 'v70', jp: '場所', reading: 'ばしょ', en: 'place', rank: 70 },
  { id: 'v71', jp: '考える', reading: 'かんがえる', en: 'think', rank: 71 },
  { id: 'v72', jp: '他', reading: 'た', en: 'other', rank: 72 },
  { id: 'v73', jp: '問題', reading: 'もんだい', en: 'problem', rank: 73 },
  { id: 'v74', jp: '子供', reading: 'こども', en: 'child', rank: 74 },
  { id: 'v75', jp: '殺す', reading: 'ころす', en: 'kill', rank: 75 },
  { id: 'v76', jp: '好き', reading: 'すき', en: 'like', rank: 76 },
  { id: 'v77', jp: '名前', reading: 'なまえ', en: 'name', rank: 77 },
  { id: 'v78', jp: '１', reading: '１', en: 'one', rank: 78 },
  { id: 'v79', jp: 'つく', reading: 'つく', en: 'reach', rank: 79 },
  { id: 'v80', jp: 'もし', reading: 'もし', en: 'if', rank: 80 },
  { id: 'v81', jp: '信ずる', reading: 'しんずる', en: 'believe', rank: 81 },
  { id: 'v82', jp: 'ダメ', reading: 'だめ', en: 'no', rank: 82 },
  { id: 'v83', jp: '皆', reading: 'みな', en: 'everyone', rank: 83 },
  { id: 'v84', jp: 'はず', reading: 'はず', en: 'should', rank: 84 },
  { id: 'v85', jp: '少し', reading: 'すこし', en: 'little', rank: 85 },
  { id: 'v86', jp: '全て', reading: 'すべて', en: 'all', rank: 86 },
  { id: 'v87', jp: '子', reading: 'こ', en: 'child', rank: 87 },
  { id: 'v88', jp: '車', reading: 'くるま', en: 'car', rank: 88 },
  { id: 'v89', jp: '後', reading: 'あと', en: 'after', rank: 89 },
  { id: 'v90', jp: '２', reading: 'に', en: 'two', rank: 90 },
  { id: 'v91', jp: '通り', reading: 'とおり', en: 'street', rank: 91 },
  { id: 'v92', jp: '目', reading: 'め', en: 'eye', rank: 92 },
  { id: 'v93', jp: 'くださる', reading: 'くださる', en: 'give', rank: 93 },
  { id: 'v94', jp: 'よく', reading: 'よく', en: 'often', rank: 94 },
  { id: 'v95', jp: '世界', reading: 'せかい', en: 'world', rank: 95 },
  { id: 'v96', jp: '方', reading: 'かた', en: 'person', rank: 96 },
  { id: 'v97', jp: '人間', reading: 'にんげん', en: 'human', rank: 97 },
  { id: 'v98', jp: '悪い', reading: 'わるい', en: 'bad', rank: 98 },
  { id: 'v99', jp: 'やめる', reading: 'やめる', en: 'quit', rank: 99 },
  { id: 'v100', jp: '欲しい', reading: 'ほしい', en: 'want', rank: 100 },
  { id: 'v101', jp: 'もっと', reading: 'もっと', en: 'more', rank: 101 },
  { id: 'v102', jp: 'つもり', reading: 'つもり', en: 'intention', rank: 102 },
  { id: 'v103', jp: 'ママ', reading: 'まま', en: 'mama', rank: 103 },
  { id: 'v104', jp: '出来る', reading: 'できる', en: 'can do', rank: 104 },
  { id: 'v105', jp: 'パパ', reading: 'ぱぱ', en: 'papa', rank: 105 },
  { id: 'v106', jp: '為', reading: 'ため', en: 'purpose', rank: 106 },
  { id: 'v107', jp: '戻る', reading: 'もどる', en: 'return', rank: 107 },
  { id: 'v108', jp: '今日', reading: 'きょう', en: 'today', rank: 108 },
  { id: 'v109', jp: '入る', reading: 'はいる', en: 'enter', rank: 109 },
  { id: 'v110', jp: '日', reading: 'ひ', en: 'day', rank: 110 },
  { id: 'v111', jp: '助ける', reading: 'たすける', en: 'help', rank: 111 },
  { id: 'v112', jp: '女', reading: 'おんな', en: 'woman', rank: 112 },
  { id: 'v113', jp: 'ごめん', reading: 'ごめん', en: 'sorry', rank: 113 },
  { id: 'v114', jp: '何', reading: 'なに', en: 'what', rank: 114 },
  { id: 'v115', jp: '心配', reading: 'しんぱい', en: 'worry', rank: 115 },
  { id: 'v116', jp: 'ところ', reading: 'ところ', en: 'place', rank: 116 },
  { id: 'v117', jp: '金', reading: 'かね', en: 'money', rank: 117 },
  { id: 'v118', jp: '母', reading: 'はは', en: 'mother', rank: 118 },
  { id: 'v119', jp: '関係', reading: 'かんけい', en: 'relation', rank: 119 },
  { id: 'v120', jp: '早い', reading: 'はやい', en: 'early', rank: 120 },
  { id: 'v121', jp: '居る', reading: 'いる', en: 'to be', rank: 121 },
  { id: 'v122', jp: '教える', reading: 'おしえる', en: 'to teach', rank: 122 },
  { id: 'v123', jp: '家族', reading: 'かぞく', en: 'family', rank: 123 },
  { id: 'v124', jp: 'すべて', reading: 'すべて', en: 'all', rank: 124 },
  { id: 'v125', jp: '連れる', reading: 'つれる', en: 'to take', rank: 125 },
  { id: 'v126', jp: '警察', reading: 'けいさつ', en: 'police', rank: 126 },
  { id: 'v127', jp: '意味', reading: 'いみ', en: 'meaning', rank: 127 },
  { id: 'v128', jp: '３', reading: 'さん', en: 'three', rank: 128 },
  { id: 'v129', jp: '願う', reading: 'ねがう', en: 'to wish', rank: 129 },
  { id: 'v130', jp: '最後', reading: 'さいご', en: 'last', rank: 130 },
  { id: 'v131', jp: '神', reading: 'かみ', en: 'god', rank: 131 },
  { id: 'v132', jp: '捜査', reading: 'そうさ', en: 'investigation', rank: 132 },
  { id: 'v133', jp: '全部', reading: 'ぜんぶ', en: 'all', rank: 133 },
  { id: 'v134', jp: '娘', reading: 'むすめ', en: 'daughter', rank: 134 },
  { id: 'v135', jp: '息子', reading: 'むすこ', en: 'son', rank: 135 },
  { id: 'v136', jp: '物', reading: 'もの', en: 'thing', rank: 136 },
  { id: 'v137', jp: '生きる', reading: 'いきる', en: 'live', rank: 137 },
  { id: 'v138', jp: '銃', reading: 'じゅう', en: 'gun', rank: 138 },
  { id: 'v139', jp: '3', reading: 'さん', en: 'three', rank: 139 },
  { id: 'v140', jp: '情報', reading: 'じょうほう', en: 'information', rank: 140 },
  { id: 'v141', jp: '入れる', reading: 'いれる', en: 'insert', rank: 141 },
  { id: 'v142', jp: 'しれる', reading: 'しれる', en: 'be known', rank: 142 },
  { id: 'v143', jp: '次', reading: 'つぎ', en: 'next', rank: 143 },
  { id: 'v144', jp: '者', reading: 'もの', en: 'person', rank: 144 },
  { id: 'v145', jp: '別', reading: 'べつ', en: 'separate', rank: 145 },
  { id: 'v146', jp: 'もちろん', reading: 'もちろん', en: 'of course', rank: 146 },
  { id: 'v147', jp: '理由', reading: 'りゆう', en: 'reason', rank: 147 },
  { id: 'v148', jp: '頭', reading: 'あたま', en: 'head', rank: 148 },
  { id: 'v149', jp: '準備', reading: 'じゅんび', en: 'preparation', rank: 149 },
  { id: 'v150', jp: 'とても', reading: 'とても', en: 'very', rank: 150 },
  { id: 'v151', jp: '愛する', reading: 'あいする', en: 'to love', rank: 151 },
  { id: 'v152', jp: 'ずっと', reading: 'ずっと', en: 'always', rank: 152 },
  { id: 'v153', jp: '一人', reading: 'ひとり', en: 'one person', rank: 153 },
  { id: 'v154', jp: '以上', reading: 'いじょう', en: 'or more', rank: 154 },
  { id: 'v155', jp: '部屋', reading: 'へや', en: 'room', rank: 155 },
  { id: 'v156', jp: '人生', reading: 'じんせい', en: 'life', rank: 156 },
  { id: 'v157', jp: '事件', reading: 'じけん', en: 'incident', rank: 157 },
  { id: 'v158', jp: '危険', reading: 'きけん', en: 'danger', rank: 158 },
  { id: 'v159', jp: '最初', reading: 'さいしょ', en: 'first', rank: 159 },
  { id: 'v160', jp: '女性', reading: 'じょせい', en: 'woman', rank: 160 },
  { id: 'v161', jp: '連絡', reading: 'れんらく', en: 'contact', rank: 161 },
  { id: 'v162', jp: 'こう', reading: 'こう', en: 'like this', rank: 162 },
  { id: 'v163', jp: '起きる', reading: 'おきる', en: 'to wake', rank: 163 },
  { id: 'v164', jp: 'みる', reading: 'みる', en: 'to see', rank: 164 },
  { id: 'v165', jp: '殺人', reading: 'さつじん', en: 'murder', rank: 165 },
  { id: 'v166', jp: '安全', reading: 'あんぜん', en: 'safety', rank: 166 },
  { id: 'v167', jp: '忘れる', reading: 'わすれる', en: 'forget', rank: 167 },
  { id: 'v168', jp: '所', reading: 'ところ', en: 'place', rank: 168 },
  { id: 'v169', jp: '覚える', reading: 'おぼえる', en: 'remember', rank: 169 },
  { id: 'v170', jp: '探す', reading: 'さがす', en: 'search', rank: 170 },
  { id: 'v171', jp: '数', reading: 'かず', en: 'number', rank: 171 },
  { id: 'v172', jp: 'まあ', reading: 'まあ', en: 'well', rank: 172 },
  { id: 'v173', jp: '分', reading: 'ぶん', en: 'minute', rank: 173 },
  { id: 'v174', jp: '約束', reading: 'やくそく', en: 'promise', rank: 174 },
  { id: 'v175', jp: '顔', reading: 'かお', en: 'face', rank: 175 },
  { id: 'v176', jp: '友達', reading: 'ともだち', en: 'friend', rank: 176 },
  { id: 'v177', jp: 'わけ', reading: 'わけ', en: 'reason', rank: 177 },
  { id: 'v178', jp: '会う', reading: 'あう', en: 'meet', rank: 178 },
  { id: 'v179', jp: '万', reading: 'まん', en: 'ten thousand', rank: 179 },
  { id: 'v180', jp: '無理', reading: 'むり', en: 'impossible', rank: 180 },
  { id: 'v181', jp: '下さる', reading: 'くださる', en: 'give', rank: 181 },
  { id: 'v182', jp: '結婚', reading: 'けっこん', en: 'marriage', rank: 182 },
  { id: 'v183', jp: 'ジョン', reading: 'じょん', en: 'John', rank: 183 },
  { id: 'v184', jp: '方法', reading: 'ほうほう', en: 'method', rank: 184 },
  { id: 'v185', jp: 'ドル', reading: 'ドル', en: 'dollar', rank: 185 },
  { id: 'v186', jp: '新しい', reading: 'あたらしい', en: 'new', rank: 186 },
  { id: 'v187', jp: '間', reading: 'あいだ', en: 'interval', rank: 187 },
  { id: 'v188', jp: '最高', reading: 'さいこう', en: 'highest', rank: 188 },
  { id: 'v189', jp: '上', reading: 'うえ', en: 'above', rank: 189 },
  { id: 'v190', jp: '頼む', reading: 'たのむ', en: 'request', rank: 190 },
  { id: 'v191', jp: '力', reading: 'ちから', en: 'power', rank: 191 },
  { id: 'v192', jp: 'I', reading: 'あい', en: 'love', rank: 192 },
  { id: 'v193', jp: '計画', reading: 'けいかく', en: 'plan', rank: 193 },
  { id: 'v194', jp: 'バカ', reading: 'バカ', en: 'idiot', rank: 194 },
  { id: 'v195', jp: '先', reading: 'さき', en: 'ahead', rank: 195 },
  { id: 'v196', jp: '仲間', reading: 'なかま', en: 'companion', rank: 196 },
  { id: 'v197', jp: 'まま', reading: 'まま', en: 'as is', rank: 197 },
  { id: 'v198', jp: 'あと', reading: 'あと', en: 'after', rank: 198 },
  { id: 'v199', jp: '見える', reading: 'みえる', en: 'visible', rank: 199 },
  { id: 'v200', jp: '心', reading: 'こころ', en: 'heart', rank: 200 },
  { id: 'v201', jp: '外', reading: 'そと', en: 'outside', rank: 201 },
  { id: 'v202', jp: '明日', reading: 'あした', en: 'tomorrow', rank: 202 },
  { id: 'v203', jp: '可能', reading: 'かのう', en: 'possible', rank: 203 },
  { id: 'v204', jp: 'どうぞ', reading: 'どうぞ', en: 'please', rank: 204 },
  { id: 'v205', jp: '夜', reading: 'よる', en: 'night', rank: 205 },
  { id: 'v206', jp: 'せい', reading: 'せい', en: 'fault', rank: 206 },
  { id: 'v207', jp: '止める', reading: 'やめる', en: 'stop', rank: 207 },
  { id: 'v208', jp: '嘘', reading: 'うそ', en: 'lie', rank: 208 },
  { id: 'v209', jp: '回', reading: 'かい', en: 'times', rank: 209 },
  { id: 'v210', jp: '確認', reading: 'かくにん', en: 'confirmation', rank: 210 },
  { id: 'v211', jp: 'また', reading: 'また', en: 'again', rank: 211 },
  { id: 'v212', jp: '全員', reading: 'ぜんいん', en: 'everyone', rank: 212 },
  { id: 'v213', jp: 'よい', reading: 'よい', en: 'good', rank: 213 },
  { id: 'v214', jp: '確か', reading: 'たしか', en: 'certain', rank: 214 },
  { id: 'v215', jp: '友人', reading: 'ゆうじん', en: 'friend', rank: 215 },
  { id: 'v216', jp: '10', reading: 'じゅう', en: 'ten', rank: 216 },
  { id: 'v217', jp: '見せる', reading: 'みせる', en: 'show', rank: 217 },
  { id: 'v218', jp: '機', reading: 'き', en: 'machine', rank: 218 },
  { id: 'v219', jp: '二人', reading: 'ふたり', en: 'two people', rank: 219 },
  { id: 'v220', jp: '理解', reading: 'りかい', en: 'understanding', rank: 220 },
  { id: 'v221', jp: '逃げる', reading: 'にげる', en: 'escape', rank: 221 },
  { id: 'v222', jp: 'とき', reading: 'とき', en: 'time', rank: 222 },
  { id: 'v223', jp: '犯人', reading: 'はんにん', en: 'criminal', rank: 223 },
  { id: 'v224', jp: '質問', reading: 'しつもん', en: 'question', rank: 224 },
  { id: 'v225', jp: '死', reading: 'し', en: 'death', rank: 225 },
  { id: 'v226', jp: '二', reading: 'に', en: 'two', rank: 226 },
  { id: 'v227', jp: 'つける', reading: 'つける', en: 'attach', rank: 227 },
  { id: 'v228', jp: '先生', reading: 'せんせい', en: 'teacher', rank: 228 },
  { id: 'v229', jp: '帰る', reading: 'かえる', en: 'return', rank: 229 },
  { id: 'v230', jp: '今夜', reading: 'こんや', en: 'tonight', rank: 230 },
  { id: 'v231', jp: '食べる', reading: 'たべる', en: 'eat', rank: 231 },
  { id: 'v232', jp: '命', reading: 'いのち', en: 'life', rank: 232 },
  { id: 'v233', jp: 'つまり', reading: 'つまり', en: 'in other words', rank: 233 },
  { id: 'v234', jp: '出す', reading: 'だす', en: 'to take out', rank: 234 },
  { id: 'v235', jp: 'L', reading: 'える', en: 'L', rank: 235 },
  { id: 'v236', jp: 'とる', reading: 'とる', en: 'to take', rank: 236 },
  { id: 'v237', jp: '妻', reading: 'つま', en: 'wife', rank: 237 },
  { id: 'v238', jp: 'だめ', reading: 'だめ', en: 'no good', rank: 238 },
  { id: 'v239', jp: '感謝', reading: 'かんしゃ', en: 'gratitude', rank: 239 },
  { id: 'v240', jp: 'ドア', reading: 'ドア', en: 'door', rank: 240 },
  { id: 'v241', jp: '博士', reading: 'はかせ', en: 'doctorate', rank: 241 },
  { id: 'v242', jp: '２人', reading: 'ふたり', en: 'two people', rank: 242 },
  { id: 'v243', jp: 'いける', reading: 'いける', en: 'can go', rank: 243 },
  { id: 'v244', jp: '写真', reading: 'しゃしん', en: 'photograph', rank: 244 },
  { id: 'v245', jp: '使う', reading: 'つかう', en: 'to use', rank: 245 },
  { id: 'v246', jp: '説明', reading: 'せつめい', en: 'explanation', rank: 246 },
  { id: 'v247', jp: '調べる', reading: 'しらべる', en: 'to investigate', rank: 247 },
  { id: 'v248', jp: '言葉', reading: 'ことば', en: 'word', rank: 248 },
  { id: 'v249', jp: '5', reading: '５', en: 'five', rank: 249 },
  { id: 'v250', jp: 'うち', reading: 'うち', en: 'inside', rank: 250 },
  { id: 'v251', jp: '失礼', reading: 'しつれい', en: 'excuse me', rank: 251 },
  { id: 'v252', jp: '野郎', reading: 'やろう', en: 'bastard', rank: 252 },
  { id: 'v253', jp: 'すごい', reading: 'すごい', en: 'amazing', rank: 253 },
  { id: 'v254', jp: 'かける', reading: 'かける', en: 'hang', rank: 254 },
  { id: 'v255', jp: 'やつ', reading: 'やつ', en: 'guy', rank: 255 },
  { id: 'v256', jp: 'よし', reading: 'よし', en: 'okay', rank: 256 },
  { id: 'v257', jp: '絶対', reading: 'ぜったい', en: 'absolutely', rank: 257 },
  { id: 'v258', jp: 'いく', reading: 'いく', en: 'go', rank: 258 },
  { id: 'v259', jp: '証拠', reading: 'しょうこ', en: 'proof', rank: 259 },
  { id: 'v260', jp: '５', reading: '５', en: 'five', rank: 260 },
  { id: 'v261', jp: '良い', reading: 'よい', en: 'good', rank: 261 },
  { id: 'v262', jp: 'ござる', reading: 'ござる', en: 'to be', rank: 262 },
  { id: 'v263', jp: '素晴らしい', reading: 'すばらしい', en: 'wonderful', rank: 263 },
  { id: 'v264', jp: '夢', reading: 'ゆめ', en: 'dream', rank: 264 },
  { id: 'v265', jp: 'すむ', reading: 'すむ', en: 'finish', rank: 265 },
  { id: 'v266', jp: '攻撃', reading: 'こうげき', en: 'attack', rank: 266 },
  { id: 'v267', jp: 'たぶん', reading: 'たぶん', en: 'probably', rank: 267 },
  { id: 'v268', jp: 'しまう', reading: 'しまう', en: 'put away', rank: 268 },
  { id: 'v269', jp: 'そんな', reading: 'そんな', en: 'such', rank: 269 },
  { id: 'v270', jp: 'きっと', reading: 'きっと', en: 'surely', rank: 270 },
  { id: 'v271', jp: '重要', reading: 'じゅうよう', en: 'important', rank: 271 },
  { id: 'v272', jp: '状況', reading: 'じょうきょう', en: 'situation', rank: 272 },
  { id: 'v273', jp: '終わり', reading: 'おわり', en: 'end', rank: 273 },
  { id: 'v274', jp: '番', reading: 'ばん', en: 'number', rank: 274 },
  { id: 'v275', jp: 'ただ', reading: 'ただ', en: 'only', rank: 275 },
  { id: 'v276', jp: '終わる', reading: 'おわる', en: 'to end', rank: 276 },
  { id: 'v277', jp: '道', reading: 'みち', en: 'road', rank: 277 },
  { id: 'v278', jp: '作る', reading: 'つくる', en: 'make', rank: 278 },
  { id: 'v279', jp: '元気', reading: 'げんき', en: 'energy', rank: 279 },
  { id: 'v280', jp: 'the', reading: 'ざ', en: 'the', rank: 280 },
  { id: 'v281', jp: '船', reading: 'ふね', en: 'ship', rank: 281 },
  { id: 'v282', jp: '取る', reading: 'とる', en: 'take', rank: 282 },
  { id: 'v283', jp: '件', reading: 'けん', en: 'matter', rank: 283 },
  { id: 'v284', jp: '父親', reading: 'ちちおや', en: 'father', rank: 284 },
  { id: 'v285', jp: '逮捕', reading: 'たいほ', en: 'arrest', rank: 285 },
  { id: 'v286', jp: '週間', reading: 'しゅうかん', en: 'week', rank: 286 },
  { id: 'v287', jp: 'なし', reading: 'なし', en: 'none', rank: 287 },
  { id: 'v288', jp: '間違い', reading: 'まちがい', en: 'mistake', rank: 288 },
  { id: 'v289', jp: '王', reading: 'おう', en: 'king', rank: 289 },
  { id: 'v290', jp: '始める', reading: 'はじめる', en: 'begin', rank: 290 },
  { id: 'v291', jp: '様', reading: 'さま', en: 'manner', rank: 291 },
  { id: 'v292', jp: '呼ぶ', reading: 'よぶ', en: 'call', rank: 292 },
  { id: 'v293', jp: '感じ', reading: 'かんじ', en: 'feeling', rank: 293 },
  { id: 'v294', jp: '同じ', reading: 'おなじ', en: 'same', rank: 294 },
  { id: 'v295', jp: '続ける', reading: 'つづける', en: 'continue', rank: 295 },
  { id: 'v296', jp: '秘密', reading: 'ひみつ', en: 'secret', rank: 296 },
  { id: 'v297', jp: '了解', reading: 'りょうかい', en: 'understood', rank: 297 },
  { id: 'v298', jp: '一番', reading: 'いちばん', en: 'best', rank: 298 },
  { id: 'v299', jp: '十分', reading: 'じゅうぶん', en: 'enough', rank: 299 },
  { id: 'v300', jp: '相手', reading: 'あいて', en: 'partner', rank: 300 },
  { id: 'v301', jp: 'ヤツ', reading: 'やつ', en: 'guy', rank: 301 },
  { id: 'v302', jp: '受ける', reading: 'うける', en: 'receive', rank: 302 },
  { id: 'v303', jp: '会社', reading: 'かいしゃ', en: 'company', rank: 303 },
  { id: 'v304', jp: '水', reading: 'みず', en: 'water', rank: 304 },
  { id: 'v305', jp: '丶', reading: 'てん', en: 'dot', rank: 305 },
  { id: 'v306', jp: '下', reading: 'した', en: 'under', rank: 306 },
  { id: 'v307', jp: '残念', reading: 'ざんねん', en: 'disappointment', rank: 307 },
  { id: 'v308', jp: '簡単', reading: 'かんたん', en: 'simple', rank: 308 },
  { id: 'v309', jp: 'チーム', reading: 'ちーむ', en: 'team', rank: 309 },
  { id: 'v310', jp: '敵', reading: 'てき', en: 'enemy', rank: 310 },
  { id: 'v311', jp: '4', reading: '4', en: 'four', rank: 311 },
  { id: 'v312', jp: '得る', reading: 'える', en: 'obtain', rank: 312 },
  { id: 'v313', jp: '血', reading: 'ち', en: 'blood', rank: 313 },
  { id: 'v314', jp: '報告', reading: 'ほうこく', en: 'report', rank: 314 },
  { id: 'v315', jp: '自由', reading: 'じゆう', en: 'freedom', rank: 315 },
  { id: 'v316', jp: '一体', reading: 'いったい', en: 'one', rank: 316 },
  { id: 'v317', jp: '警官', reading: 'けいかん', en: 'policeman', rank: 317 },
  { id: 'v318', jp: '大統領', reading: 'だいとうりょう', en: 'president', rank: 318 },
  { id: 'v319', jp: '命令', reading: 'めいれい', en: 'order', rank: 319 },
  { id: 'v320', jp: 'you', reading: 'you', en: 'you', rank: 320 },
  { id: 'v321', jp: '多く', reading: 'おおく', en: 'many', rank: 321 },
  { id: 'v322', jp: '自身', reading: 'じしん', en: 'oneself', rank: 322 },
  { id: 'v323', jp: '真実', reading: 'しんじつ', en: 'truth', rank: 323 },
  { id: 'v324', jp: '感ずる', reading: 'かんずる', en: 'feel', rank: 324 },
  { id: 'v325', jp: 'ほう', reading: 'ほう', en: 'direction', rank: 325 },
  { id: 'v326', jp: '昔', reading: 'むかし', en: 'long ago', rank: 326 },
  { id: 'v327', jp: '犯罪', reading: 'はんざい', en: 'crime', rank: 327 },
  { id: 'v328', jp: '街', reading: 'まち', en: 'town', rank: 328 },
  { id: 'v329', jp: '学校', reading: 'がっこう', en: 'school', rank: 329 },
  { id: 'v330', jp: '人々', reading: 'ひとびと', en: 'people', rank: 330 },
  { id: 'v331', jp: '初めて', reading: 'はじめて', en: 'first time', rank: 331 },
  { id: 'v332', jp: '口', reading: 'くち', en: 'mouth', rank: 332 },
  { id: 'v333', jp: '元', reading: 'もと', en: 'origin', rank: 333 },
  { id: 'v334', jp: 'アメリカ', reading: 'アメリカ', en: 'America', rank: 334 },
  { id: 'v335', jp: 'うまい', reading: 'うまい', en: 'delicious', rank: 335 },
  { id: 'v336', jp: '刑事', reading: 'けいじ', en: 'detective', rank: 336 },
  { id: 'v337', jp: '大変', reading: 'たいへん', en: 'terrible', rank: 337 },
  { id: 'v338', jp: '声', reading: 'こえ', en: 'voice', rank: 338 },
  { id: 'v339', jp: '考え', reading: 'かんがえ', en: 'thought', rank: 339 },
  { id: 'v340', jp: '寝る', reading: 'ねる', en: 'sleep', rank: 340 },
  { id: 'v341', jp: '４', reading: 'よん', en: 'four', rank: 341 },
  { id: 'v342', jp: '戦争', reading: 'せんそう', en: 'war', rank: 342 },
  { id: 'v343', jp: '母親', reading: 'ははおや', en: 'mother', rank: 343 },
  { id: 'v344', jp: '与える', reading: 'あたえる', en: 'give', rank: 344 },
  { id: 'v345', jp: '離れる', reading: 'はなれる', en: 'leave', rank: 345 },
  { id: 'v346', jp: '伝える', reading: 'つたえる', en: 'tell', rank: 346 },
  { id: 'v347', jp: '奥', reading: 'おく', en: 'back', rank: 347 },
  { id: 'v348', jp: '記録', reading: 'きろく', en: 'record', rank: 348 },
  { id: 'v349', jp: '変', reading: 'へん', en: 'strange', rank: 349 },
  { id: 'v350', jp: '気持ち', reading: 'きもち', en: 'feeling', rank: 350 },
  { id: 'v351', jp: '聞こえる', reading: 'きこえる', en: 'hear', rank: 351 },
  { id: 'v352', jp: '武器', reading: 'ぶき', en: 'weapon', rank: 352 },
  { id: 'v353', jp: 'もん', reading: 'もん', en: 'thing', rank: 353 },
  { id: 'v354', jp: '置く', reading: 'おく', en: 'put', rank: 354 },
  { id: 'v355', jp: 'FBI', reading: 'えふびーあい', en: 'FBI', rank: 355 },
  { id: 'v356', jp: '助け', reading: 'たすけ', en: 'help', rank: 356 },
  { id: 'v357', jp: '冗談', reading: 'じょうだん', en: 'joke', rank: 357 },
  { id: 'v358', jp: '監視', reading: 'かんし', en: 'monitoring', rank: 358 },
  { id: 'v359', jp: '書く', reading: 'かく', en: 'write', rank: 359 },
  { id: 'v360', jp: '行動', reading: 'こうどう', en: 'action', rank: 360 },
  { id: 'v361', jp: '病院', reading: 'びょういん', en: 'hospital', rank: 361 },
  { id: 'v362', jp: '責任', reading: 'せきにん', en: 'responsibility', rank: 362 },
  { id: 'v363', jp: '間違う', reading: 'まちがう', en: 'mistake', rank: 363 },
  { id: 'v364', jp: '座る', reading: 'すわる', en: 'sit', rank: 364 },
  { id: 'v365', jp: '実', reading: 'み', en: 'fruit', rank: 365 },
  { id: 'v366', jp: '国', reading: 'くに', en: 'country', rank: 366 },
  { id: 'v367', jp: 'a', reading: 'a', en: 'a', rank: 367 },
  { id: 'v368', jp: '普通', reading: 'ふつう', en: 'normal', rank: 368 },
  { id: 'v369', jp: '多分', reading: 'たぶん', en: 'probably', rank: 369 },
  { id: 'v370', jp: '役', reading: 'やく', en: 'role', rank: 370 },
  { id: 'v371', jp: 'まず', reading: 'まず', en: 'first', rank: 371 },
  { id: 'v372', jp: '行ける', reading: 'いける', en: 'can go', rank: 372 },
  { id: 'v373', jp: '存在', reading: 'そんざい', en: 'existence', rank: 373 },
  { id: 'v374', jp: '協力', reading: 'きょうりょく', en: 'cooperation', rank: 374 },
  { id: 'v375', jp: '軍', reading: 'ぐん', en: 'army', rank: 375 },
  { id: 'v376', jp: '頃', reading: 'ころ', en: 'about', rank: 376 },
  { id: 'v377', jp: '実際', reading: 'じっさい', en: 'reality', rank: 377 },
  { id: 'v378', jp: '守る', reading: 'まもる', en: 'protect', rank: 378 },
  { id: 'v379', jp: '生活', reading: 'せいかつ', en: 'life', rank: 379 },
  { id: 'v380', jp: '気分', reading: 'きぶん', en: 'feeling', rank: 380 },
  { id: 'v381', jp: '嫌', reading: 'いや', en: 'disagreeable', rank: 381 },
  { id: 'v382', jp: '被害', reading: 'ひがい', en: 'damage', rank: 382 },
  { id: 'v383', jp: '解決', reading: 'かいけつ', en: 'solution', rank: 383 },
  { id: 'v384', jp: '開ける', reading: 'あける', en: 'open', rank: 384 },
  { id: 'v385', jp: 'かなり', reading: 'かなり', en: 'considerably', rank: 385 },
  { id: 'v386', jp: '６', reading: '６', en: 'six', rank: 386 },
  { id: 'v387', jp: '調査', reading: 'ちょうさ', en: 'investigation', rank: 387 },
  { id: 'v388', jp: '本', reading: 'ほん', en: 'book', rank: 388 },
  { id: 'v389', jp: 'ヶ月', reading: 'かげつ', en: 'months', rank: 389 },
  { id: 'v390', jp: '兄', reading: 'あに', en: 'older brother', rank: 390 },
  { id: 'v391', jp: '正しい', reading: 'ただしい', en: 'correct', rank: 391 },
  { id: 'v392', jp: '結果', reading: 'けっか', en: 'result', rank: 392 },
  { id: 'v393', jp: '送る', reading: 'おくる', en: 'send', rank: 393 },
  { id: 'v394', jp: '会', reading: 'かい', en: 'meeting', rank: 394 },
  { id: 'v395', jp: 'カメラ', reading: 'かめら', en: 'camera', rank: 395 },
  { id: 'v396', jp: '番号', reading: 'ばんごう', en: 'number', rank: 396 },
  { id: 'v397', jp: '携帯', reading: 'けいたい', en: 'cellphone', rank: 397 },
  { id: 'v398', jp: '１人', reading: 'ひとり', en: 'one person', rank: 398 },
  { id: 'v399', jp: '働く', reading: 'はたらく', en: 'work', rank: 399 },
  { id: 'v400', jp: '犬', reading: 'いぬ', en: 'dog', rank: 400 },
  { id: 'v401', jp: '向かう', reading: 'むかう', en: 'head towards', rank: 401 },
  { id: 'v402', jp: 'ボス', reading: 'ぼす', en: 'boss', rank: 402 },
  { id: 'v403', jp: '愛', reading: 'あい', en: 'love', rank: 403 },
  { id: 'v404', jp: '状態', reading: 'じょうたい', en: 'state', rank: 404 },
  { id: 'v405', jp: '興味', reading: 'きょうみ', en: 'interest', rank: 405 },
  { id: 'v406', jp: '研究', reading: 'けんきゅう', en: 'research', rank: 406 },
  { id: 'v407', jp: '大事', reading: 'だいじ', en: 'important', rank: 407 },
  { id: 'v408', jp: 'ほしい', reading: 'ほしい', en: 'want', rank: 408 },
  { id: 'v409', jp: '運転', reading: 'うんてん', en: 'driving', rank: 409 },
  { id: 'v410', jp: 'マジ', reading: 'まじ', en: 'seriously', rank: 410 },
  { id: 'v411', jp: '発見', reading: 'はっけん', en: 'discovery', rank: 411 },
  { id: 'v412', jp: '刑務', reading: 'けいむ', en: 'prison affairs', rank: 412 },
  { id: 'v413', jp: '以外', reading: 'いがい', en: 'except', rank: 413 },
  { id: 'v414', jp: '夫', reading: 'おっと', en: 'husband', rank: 414 },
  { id: 'v415', jp: '乗る', reading: 'のる', en: 'ride', rank: 415 },
  { id: 'v416', jp: '6', reading: 'ろく', en: 'six', rank: 416 },
  { id: 'v417', jp: '消える', reading: 'きえる', en: 'disappear', rank: 417 },
  { id: 'v418', jp: 'すぎる', reading: 'すぎる', en: 'exceed', rank: 418 },
  { id: 'v419', jp: '隠す', reading: 'かくす', en: 'hide', rank: 419 },
  { id: 'v420', jp: '弁護', reading: 'べんご', en: 'defense', rank: 420 },
  { id: 'v421', jp: '幸せ', reading: 'しあわせ', en: 'happiness', rank: 421 },
  { id: 'v422', jp: '兄弟', reading: 'きょうだい', en: 'siblings', rank: 422 },
  { id: 'v423', jp: '変わる', reading: 'かわる', en: 'change', rank: 423 },
  { id: 'v424', jp: 'ひどい', reading: 'ひどい', en: 'terrible', rank: 424 },
  { id: 'v425', jp: 'ゲーム', reading: 'げーむ', en: 'game', rank: 425 },
  { id: 'v426', jp: '飛行', reading: 'ひこう', en: 'flight', rank: 426 },
  { id: 'v427', jp: '破壊', reading: 'はかい', en: 'destruction', rank: 427 },
  { id: 'v428', jp: 'チャンス', reading: 'チャンス', en: 'chance', rank: 428 },
  { id: 'v429', jp: '静か', reading: 'しずか', en: 'quiet', rank: 429 },
  { id: 'v430', jp: 'ジェーン', reading: 'ジェーン', en: 'Jane', rank: 430 },
  { id: 'v431', jp: 's', reading: 'ｓ', en: 's', rank: 431 },
  { id: 'v432', jp: '地球', reading: 'ちきゅう', en: 'earth', rank: 432 },
  { id: 'v433', jp: '足', reading: 'あし', en: 'foot', rank: 433 },
  { id: 'v434', jp: '昨日', reading: 'きのう', en: 'yesterday', rank: 434 },
  { id: 'v435', jp: '信用', reading: 'しんよう', en: 'trust', rank: 435 },
  { id: 'v436', jp: '目的', reading: 'もくてき', en: 'purpose', rank: 436 },
  { id: 'v437', jp: '今度', reading: 'こんど', en: 'next time', rank: 437 },
  { id: 'v438', jp: '死体', reading: 'したい', en: 'corpse', rank: 438 },
  { id: 'v439', jp: '願い', reading: 'ねがい', en: 'wish', rank: 439 },
  { id: 'v440', jp: 'よる', reading: 'よる', en: 'due to', rank: 440 },
  { id: 'v441', jp: 'ジャック', reading: 'ジャック', en: 'jack', rank: 441 },
  { id: 'v442', jp: '医者', reading: 'いしゃ', en: 'doctor', rank: 442 },
  { id: 'v443', jp: 'ウソ', reading: 'ウソ', en: 'lie', rank: 443 },
  { id: 'v444', jp: '特別', reading: 'とくべつ', en: 'special', rank: 444 },
  { id: 'v445', jp: 'あまり', reading: 'あまり', en: 'remainder', rank: 445 },
  { id: 'v446', jp: '近く', reading: 'ちかく', en: 'nearby', rank: 446 },
  { id: 'v447', jp: 'す', reading: 'す', en: 'do', rank: 447 },
  { id: 'v448', jp: '朝', reading: 'あさ', en: 'morning', rank: 448 },
  { id: 'v449', jp: '後ろ', reading: 'うしろ', en: 'behind', rank: 449 },
  { id: 'v450', jp: '取引', reading: 'とりひき', en: 'transaction', rank: 450 },
  { id: 'v451', jp: '邪魔', reading: 'じゃま', en: 'hindrance', rank: 451 },
  { id: 'v452', jp: '客', reading: 'きゃく', en: 'guest', rank: 452 },
  { id: 'v453', jp: '会える', reading: 'あえる', en: 'can meet', rank: 453 },
  { id: 'v454', jp: '装置', reading: 'そうち', en: 'device', rank: 454 },
  { id: 'v455', jp: '不明', reading: 'ふめい', en: 'unclear', rank: 455 },
  { id: 'v456', jp: '互い', reading: 'たがい', en: 'mutual', rank: 456 },
  { id: 'v457', jp: 'ｱﾙﾏﾝ', reading: 'あるまん', en: 'Arman', rank: 457 },
  { id: 'v458', jp: '買う', reading: 'かう', en: 'buy', rank: 458 },
  { id: 'v459', jp: '名', reading: 'な', en: 'name', rank: 459 },
  { id: 'v460', jp: '連中', reading: 'れんちゅう', en: 'gang', rank: 460 },
  { id: 'v461', jp: '限り', reading: 'かぎり', en: 'limit', rank: 461 },
  { id: 'v462', jp: '場合', reading: 'ばあい', en: 'case', rank: 462 },
  { id: 'v463', jp: '美咲', reading: 'みさき', en: 'Misaki', rank: 463 },
  { id: 'v464', jp: '現場', reading: 'げんば', en: 'scene', rank: 464 },
  { id: 'v465', jp: '唯一', reading: 'ゆいいつ', en: 'only', rank: 465 },
  { id: 'v466', jp: 'to', reading: 'と', en: 'and', rank: 466 },
  { id: 'v467', jp: '長い', reading: 'ながい', en: 'long', rank: 467 },
  { id: 'v468', jp: 'おく', reading: 'おく', en: 'put', rank: 468 },
  { id: 'v469', jp: '用意', reading: 'ようい', en: 'preparation', rank: 469 },
  { id: 'v470', jp: '何故', reading: 'なぜ', en: 'why', rank: 470 },
  { id: 'v471', jp: '最近', reading: 'さいきん', en: 'recently', rank: 471 },
  { id: 'v472', jp: '失敗', reading: 'しっぱい', en: 'failure', rank: 472 },
  { id: 'v473', jp: '失う', reading: 'うしなう', en: 'lose', rank: 473 },
  { id: 'v474', jp: '映画', reading: 'えいが', en: 'movie', rank: 474 },
  { id: 'v475', jp: '政府', reading: 'せいふ', en: 'government', rank: 475 },
  { id: 'v476', jp: '動く', reading: 'うごく', en: 'move', rank: 476 },
  { id: 'v477', jp: '選択', reading: 'せんたく', en: 'selection', rank: 477 },
  { id: 'v478', jp: '犠牲', reading: 'ぎせい', en: 'sacrifice', rank: 478 },
  { id: 'v479', jp: '全く', reading: 'まったく', en: 'entirely', rank: 479 },
  { id: 'v480', jp: '起こる', reading: 'おこる', en: 'to happen', rank: 480 },
  { id: 'v481', jp: '急ぐ', reading: 'いそぐ', en: 'to hurry', rank: 481 },
  { id: 'v482', jp: '過去', reading: 'かこ', en: 'past', rank: 482 },
  { id: 'v483', jp: '弟', reading: 'おとうと', en: 'younger brother', rank: 483 },
  { id: 'v484', jp: '信頼', reading: 'しんらい', en: 'trust', rank: 484 },
  { id: 'v485', jp: '飲む', reading: 'のむ', en: 'to drink', rank: 485 },
  { id: 'v486', jp: '嫌い', reading: 'きらい', en: 'dislike', rank: 486 },
  { id: 'v487', jp: '精神', reading: 'せいしん', en: 'mind', rank: 487 },
  { id: 'v488', jp: 'たくさん', reading: 'たくさん', en: 'a lot', rank: 488 },
  { id: 'v489', jp: 'とこ', reading: 'ところ', en: 'place', rank: 489 },
  { id: 'v490', jp: '事故', reading: 'じこ', en: 'accident', rank: 490 },
  { id: 'v491', jp: '記憶', reading: 'きおく', en: 'memory', rank: 491 },
  { id: 'v492', jp: '姿', reading: 'すがた', en: 'figure', rank: 492 },
  { id: 'v493', jp: '妹', reading: 'いもうと', en: 'younger sister', rank: 493 },
  { id: 'v494', jp: '変える', reading: 'かえる', en: 'to change', rank: 494 },
  { id: 'v495', jp: '完全', reading: 'かんぜん', en: 'complete', rank: 495 },
  { id: 'v496', jp: '20', reading: 'にじゅう', en: 'twenty', rank: 496 },
  { id: 'v497', jp: '人物', reading: 'じんぶつ', en: 'character', rank: 497 },
  { id: 'v498', jp: 'ちゃんと', reading: 'ちゃんと', en: 'properly', rank: 498 },
  { id: 'v499', jp: '店', reading: 'みせ', en: 'store', rank: 499 },
  { id: 'v500', jp: '移動', reading: 'いどう', en: 'movement', rank: 500 },
  { id: 'v501', jp: '撃つ', reading: 'うつ', en: 'shoot', rank: 501 },
  { id: 'v502', jp: 'まさか', reading: 'まさか', en: 'no way', rank: 502 },
  { id: 'v503', jp: '町', reading: 'まち', en: 'town', rank: 503 },
  { id: 'v504', jp: '素敵', reading: 'すてき', en: 'lovely', rank: 504 },
  { id: 'v505', jp: '女の子', reading: 'おんなのこ', en: 'girl', rank: 505 },
  { id: 'v506', jp: 'もらう', reading: 'もらう', en: 'receive', rank: 506 },
  { id: 'v507', jp: '服', reading: 'ふく', en: 'clothes', rank: 507 },
  { id: 'v508', jp: '警備', reading: 'けいび', en: 'security', rank: 508 },
  { id: 'v509', jp: '鍵', reading: 'かぎ', en: 'key', rank: 509 },
  { id: 'v510', jp: '部', reading: 'ぶ', en: 'part', rank: 510 },
  { id: 'v511', jp: 'とおり', reading: 'とおり', en: 'street', rank: 511 },
  { id: 'v512', jp: '語', reading: 'ご', en: 'language', rank: 512 },
  { id: 'v513', jp: '無事', reading: 'ぶじ', en: 'safe', rank: 513 },
  { id: 'v514', jp: '裁判', reading: 'さいばん', en: 'trial', rank: 514 },
  { id: 'v515', jp: '怖い', reading: 'こわい', en: 'scary', rank: 515 },
  { id: 'v516', jp: 'とにかく', reading: 'とにかく', en: 'anyway', rank: 516 },
  { id: 'v517', jp: '両親', reading: 'りょうしん', en: 'parents', rank: 517 },
  { id: 'v518', jp: 'ビル', reading: 'ビル', en: 'building', rank: 518 },
  { id: 'v519', jp: '残る', reading: 'のこる', en: 'remain', rank: 519 },
  { id: 'v520', jp: '罪', reading: 'つみ', en: 'sin', rank: 520 },
  { id: 'v521', jp: '価値', reading: 'かち', en: 'value', rank: 521 },
  { id: 'v522', jp: 'システム', reading: 'システム', en: 'system', rank: 522 },
  { id: 'v523', jp: '想像', reading: 'そうぞう', en: 'imagination', rank: 523 },
  { id: 'v524', jp: '音', reading: 'おと', en: 'sound', rank: 524 },
  { id: 'v525', jp: 'サム', reading: 'サム', en: 'Sam', rank: 525 },
  { id: 'v526', jp: '必ず', reading: 'かならず', en: 'certainly', rank: 526 },
  { id: 'v527', jp: '読む', reading: 'よむ', en: 'read', rank: 527 },
  { id: 'v528', jp: '望む', reading: 'のぞむ', en: 'desire', rank: 528 },
  { id: 'v529', jp: '言える', reading: 'いえる', en: 'can say', rank: 529 },
  { id: 'v530', jp: '嬉しい', reading: 'うれしい', en: 'happy', rank: 530 },
  { id: 'v531', jp: '以前', reading: 'いぜん', en: 'before', rank: 531 },
  { id: 'v532', jp: 'まるで', reading: 'まるで', en: 'just like', rank: 532 },
  { id: 'v533', jp: '黙る', reading: 'だまる', en: 'be silent', rank: 533 },
  { id: 'v534', jp: '馬鹿', reading: 'ばか', en: 'idiot', rank: 534 },
  { id: 'v535', jp: '住む', reading: 'すむ', en: 'live', rank: 535 },
  { id: 'v536', jp: '体', reading: 'からだ', en: 'body', rank: 536 },
  { id: 'v537', jp: '決める', reading: 'きめる', en: 'decide', rank: 537 },
  { id: 'v538', jp: '銀行', reading: 'ぎんこう', en: 'bank', rank: 538 },
  { id: 'v539', jp: '最も', reading: 'もっとも', en: 'most', rank: 539 },
  { id: 'v540', jp: '共', reading: 'とも', en: 'together', rank: 540 },
  { id: 'v541', jp: '非常', reading: 'ひじょう', en: 'emergency', rank: 541 },
  { id: 'v542', jp: '容疑', reading: 'ようぎ', en: 'suspicion', rank: 542 },
  { id: 'v543', jp: 'ショー', reading: 'しょー', en: 'show', rank: 543 },
  { id: 'v544', jp: '壁', reading: 'かべ', en: 'wall', rank: 544 },
  { id: 'v545', jp: '証明', reading: 'しょうめい', en: 'proof', rank: 545 },
  { id: 'v546', jp: '身', reading: 'み', en: 'body', rank: 546 },
  { id: 'v547', jp: '月', reading: 'つき', en: 'moon', rank: 547 },
  { id: 'v548', jp: '年間', reading: 'ねんかん', en: 'year', rank: 548 },
  { id: 'v549', jp: '経験', reading: 'けいけん', en: 'experience', rank: 549 },
  { id: 'v550', jp: '爆弾', reading: 'ばくだん', en: 'bomb', rank: 550 },
  { id: 'v551', jp: '今回', reading: 'こんかい', en: 'this time', rank: 551 },
  { id: 'v552', jp: 'あげる', reading: 'あげる', en: 'to give', rank: 552 },
  { id: 'v553', jp: '決して', reading: 'けっして', en: 'never', rank: 553 },
  { id: 'v554', jp: '正直', reading: 'しょうじき', en: 'honest', rank: 554 },
  { id: 'v555', jp: '薬', reading: 'くすり', en: 'medicine', rank: 555 },
  { id: 'v556', jp: '本物', reading: 'ほんもの', en: 'genuine article', rank: 556 },
  { id: 'v557', jp: 'ピーター', reading: 'ぴーたー', en: 'Peter', rank: 557 },
  { id: 'v558', jp: '落ち着く', reading: 'おちつく', en: 'calm down', rank: 558 },
  { id: 'v559', jp: 'メール', reading: 'めーる', en: 'mail', rank: 559 },
  { id: 'v560', jp: '未来', reading: 'みらい', en: 'future', rank: 560 },
  { id: 'v561', jp: '大学', reading: 'だいがく', en: 'university', rank: 561 },
  { id: 'v562', jp: '結構', reading: 'けっこう', en: 'splendid', rank: 562 },
  { id: 'v563', jp: '病気', reading: 'びょうき', en: 'illness', rank: 563 },
  { id: 'v564', jp: '用', reading: 'よう', en: 'business', rank: 564 },
  { id: 'v565', jp: '宇宙', reading: 'うちゅう', en: 'universe', rank: 565 },
  { id: 'v566', jp: '治療', reading: 'ちりょう', en: 'treatment', rank: 566 },
  { id: 'v567', jp: 'リスト', reading: 'リスト', en: 'list', rank: 567 },
  { id: 'v568', jp: '予定', reading: 'よてい', en: 'plan', rank: 568 },
  { id: 'v569', jp: '捕まえる', reading: 'つかまえる', en: 'to catch', rank: 569 },
  { id: 'v570', jp: '盗む', reading: 'ぬすむ', en: 'to steal', rank: 570 },
  { id: 'v571', jp: '最悪', reading: 'さいあく', en: 'worst', rank: 571 },
  { id: 'v572', jp: '完璧', reading: 'かんぺき', en: 'perfect', rank: 572 },
  { id: 'v573', jp: 'ホテル', reading: 'ホテル', en: 'hotel', rank: 573 },
  { id: 'v574', jp: '任務', reading: 'にんむ', en: 'duty', rank: 574 },
  { id: 'v575', jp: '注意', reading: 'ちゅうい', en: 'caution', rank: 575 },
  { id: 'v576', jp: '30', reading: '３０', en: 'thirty', rank: 576 },
  { id: 'v577', jp: '許可', reading: 'きょか', en: 'permission', rank: 577 },
  { id: 'v578', jp: '無駄', reading: 'むだ', en: 'useless', rank: 578 },
  { id: 'v579', jp: '腕', reading: 'うで', en: 'arm', rank: 579 },
  { id: 'v580', jp: '向こう', reading: 'むこう', en: 'over there', rank: 580 },
  { id: 'v581', jp: '本気', reading: 'ほんき', en: 'serious', rank: 581 },
  { id: 'v582', jp: '全然', reading: 'ぜんぜん', en: 'not at all', rank: 582 },
  { id: 'v583', jp: '勇気', reading: 'ゆうき', en: 'courage', rank: 583 },
  { id: 'v584', jp: '信じる', reading: 'しんじる', en: 'believe', rank: 584 },
  { id: 'v585', jp: '秒', reading: 'びょう', en: 'second', rank: 585 },
  { id: 'v586', jp: '渡す', reading: 'わたす', en: 'hand over', rank: 586 },
  { id: 'v587', jp: '事実', reading: 'じじつ', en: 'fact', rank: 587 },
  { id: 'v588', jp: '傷', reading: 'きず', en: 'wound', rank: 588 },
  { id: 'v589', jp: 'マン', reading: 'マン', en: 'man', rank: 589 },
  { id: 'v590', jp: '姉', reading: 'あね', en: 'older sister', rank: 590 },
  { id: 'v591', jp: '訳', reading: 'わけ', en: 'reason', rank: 591 },
  { id: 'v592', jp: '着る', reading: 'きる', en: 'wear', rank: 592 },
  { id: 'v593', jp: '法', reading: 'ほう', en: 'law', rank: 593 },
  { id: 'v594', jp: 'ホント', reading: 'ホント', en: 'really', rank: 594 },
  { id: 'v595', jp: 'パーティー', reading: 'パーティー', en: 'party', rank: 595 },
  { id: 'v596', jp: '成功', reading: 'せいこう', en: 'success', rank: 596 },
  { id: 'v597', jp: '科学', reading: 'かがく', en: 'science', rank: 597 },
  { id: 'v598', jp: '過ぎる', reading: 'すぎる', en: 'pass', rank: 598 },
  { id: 'v599', jp: 'バー', reading: 'バー', en: 'bar', rank: 599 },
  { id: 'v600', jp: 'コーヒー', reading: 'コーヒー', en: 'coffee', rank: 600 },
  { id: 'v601', jp: 'カード', reading: 'かーど', en: 'card', rank: 601 },
  { id: 'v602', jp: '８', reading: 'はち', en: 'eight', rank: 602 },
  { id: 'v603', jp: '違い', reading: 'ちがい', en: 'difference', rank: 603 },
  { id: 'v604', jp: 'さっき', reading: 'さっき', en: 'a while ago', rank: 604 },
  { id: 'v605', jp: 'ベッド', reading: 'べっど', en: 'bed', rank: 605 },
  { id: 'v606', jp: '感じる', reading: 'かんじる', en: 'feel', rank: 606 },
  { id: 'v607', jp: '首', reading: 'くび', en: 'neck', rank: 607 },
  { id: 'v608', jp: '爆発', reading: 'ばくはつ', en: 'explosion', rank: 608 },
  { id: 'v609', jp: '昨夜', reading: 'ゆうべ', en: 'last night', rank: 609 },
  { id: 'v610', jp: '地下', reading: 'ちか', en: 'basement', rank: 610 },
  { id: 'v611', jp: '組織', reading: 'そしき', en: 'organization', rank: 611 },
  { id: 'v612', jp: '少年', reading: 'しょうねん', en: 'boy', rank: 612 },
  { id: 'v613', jp: '作戦', reading: 'さくせん', en: 'tactic', rank: 613 },
  { id: 'v614', jp: '美しい', reading: 'うつくしい', en: 'beautiful', rank: 614 },
  { id: 'v615', jp: 'ミス', reading: 'みす', en: 'mistake', rank: 615 },
  { id: 'v616', jp: '現実', reading: 'げんじつ', en: 'reality', rank: 616 },
  { id: 'v617', jp: '調子', reading: 'ちょうし', en: 'condition', rank: 617 },
  { id: 'v618', jp: 'ニック', reading: 'にっく', en: 'nick', rank: 618 },
  { id: 'v619', jp: '魔法', reading: 'まほう', en: 'magic', rank: 619 },
  { id: 'v620', jp: '答え', reading: 'こたえ', en: 'answer', rank: 620 },
  { id: 'v621', jp: '7', reading: '７', en: 'seven', rank: 621 },
  { id: 'v622', jp: 'マイク', reading: 'まいく', en: 'microphone', rank: 622 },
  { id: 'v623', jp: '時代', reading: 'じだい', en: 'era', rank: 623 },
  { id: 'v624', jp: 'ほとんど', reading: 'ほとんど', en: 'mostly', rank: 624 },
  { id: 'v625', jp: 'キス', reading: 'きす', en: 'kiss', rank: 625 },
  { id: 'v626', jp: '患者', reading: 'かんじゃ', en: 'patient', rank: 626 },
  { id: 'v627', jp: '見つかる', reading: 'みつかる', en: 'be found', rank: 627 },
  { id: 'v628', jp: 'デート', reading: 'でーと', en: 'date', rank: 628 },
  { id: 'v629', jp: '点', reading: 'てん', en: 'point', rank: 629 },
  { id: 'v630', jp: 'ゆっくり', reading: 'ゆっくり', en: 'slowly', rank: 630 },
  { id: 'v631', jp: '個人', reading: 'こじん', en: 'individual', rank: 631 },
  { id: 'v632', jp: '落ちる', reading: 'おちる', en: 'fall', rank: 632 },
  { id: 'v633', jp: '答える', reading: 'こたえる', en: 'answer', rank: 633 },
  { id: 'v634', jp: 'ニュース', reading: 'にゅーす', en: 'news', rank: 634 },
  { id: 'v635', jp: '毎日', reading: 'まいにち', en: 'every day', rank: 635 },
  { id: 'v636', jp: 'レッド', reading: 'れっど', en: 'red', rank: 636 },
  { id: 'v637', jp: '追跡', reading: 'ついせき', en: 'tracking', rank: 637 },
  { id: 'v638', jp: '期待', reading: 'きたい', en: 'expectation', rank: 638 },
  { id: 'v639', jp: '陛下', reading: 'へいか', en: 'majesty', rank: 639 },
  { id: 'v640', jp: '当然', reading: 'とうぜん', en: 'naturally', rank: 640 },
  { id: 'v641', jp: 'しっかり', reading: 'しっかり', en: 'firmly', rank: 641 },
  { id: 'v642', jp: '無し', reading: 'なし', en: 'without', rank: 642 },
  { id: 'v643', jp: '利用', reading: 'りよう', en: 'use', rank: 643 },
  { id: 'v644', jp: '今朝', reading: 'けさ', en: 'this morning', rank: 644 },
  { id: 'v645', jp: '地', reading: 'ち', en: 'ground', rank: 645 },
  { id: 'v646', jp: '保護', reading: 'ほご', en: 'protection', rank: 646 },
  { id: 'v647', jp: '州', reading: 'しゅう', en: 'state', rank: 647 },
  { id: 'v648', jp: '古い', reading: 'ふるい', en: 'old', rank: 648 },
  { id: 'v649', jp: '求める', reading: 'もとめる', en: 'seek', rank: 649 },
  { id: 'v650', jp: '主人', reading: 'しゅじん', en: 'master', rank: 650 },
  { id: 'v651', jp: '訓練', reading: 'くんれん', en: 'training', rank: 651 },
  { id: 'v652', jp: 'ジョー', reading: 'じょー', en: 'Joe', rank: 652 },
  { id: 'v653', jp: '残り', reading: 'のこり', en: 'remainder', rank: 653 },
  { id: 'v654', jp: '技術', reading: 'ぎじゅつ', en: 'technology', rank: 654 },
  { id: 'v655', jp: 'おかしい', reading: 'おかしい', en: 'strange', rank: 655 },
  { id: 'v656', jp: '手伝う', reading: 'てつだう', en: 'help', rank: 656 },
  { id: 'v657', jp: '戦い', reading: 'たたかい', en: 'battle', rank: 657 },
  { id: 'v658', jp: '面白い', reading: 'おもしろい', en: 'interesting', rank: 658 },
  { id: 'v659', jp: 'いや', reading: 'いや', en: 'disagreeable', rank: 659 },
  { id: 'v660', jp: '強い', reading: 'つよい', en: 'strong', rank: 660 },
  { id: 'v661', jp: '申し訳', reading: 'もうしわけ', en: 'apology', rank: 661 },
  { id: 'v662', jp: '脳', reading: 'のう', en: 'brain', rank: 662 },
  { id: 'v663', jp: '望み', reading: 'のぞみ', en: 'wish', rank: 663 },
  { id: 'v664', jp: '8', reading: '８', en: 'eight', rank: 664 },
  { id: 'v665', jp: 'かかる', reading: 'かかる', en: 'take', rank: 665 },
  { id: 'v666', jp: 'ニューヨーク', reading: 'ニューヨーク', en: 'new york', rank: 666 },
  { id: 'v667', jp: '捨てる', reading: 'すてる', en: 'throw away', rank: 667 },
  { id: 'v668', jp: '三', reading: 'さん', en: 'three', rank: 668 },
  { id: 'v669', jp: '上手い', reading: 'うまい', en: 'skillful', rank: 669 },
  { id: 'v670', jp: '明らか', reading: 'あきらか', en: 'obvious', rank: 670 },
  { id: 'v671', jp: '少ない', reading: 'すくない', en: 'few', rank: 671 },
  { id: 'v672', jp: '難しい', reading: 'むずかしい', en: 'difficult', rank: 672 },
  { id: 'v673', jp: '警部', reading: 'けいぶ', en: 'police inspector', rank: 673 },
  { id: 'v674', jp: 'ベン', reading: 'べん', en: 'Ben', rank: 674 },
  { id: 'v675', jp: '動物', reading: 'どうぶつ', en: 'animal', rank: 675 },
  { id: 'v676', jp: '船長', reading: 'せんちょう', en: 'captain', rank: 676 },
  { id: 'v677', jp: 'まったく', reading: 'まったく', en: 'entirely', rank: 677 },
  { id: 'v678', jp: '平気', reading: 'へいき', en: 'calm', rank: 678 },
  { id: 'v679', jp: '検査', reading: 'けんさ', en: 'inspection', rank: 679 },
  { id: 'v680', jp: 'めでたい', reading: 'めでたい', en: 'auspicious', rank: 680 },
  { id: 'v681', jp: '理子', reading: 'みちこ', en: 'Michiko', rank: 681 },
  { id: 'v682', jp: '15', reading: '１５', en: 'fifteen', rank: 682 },
  { id: 'v683', jp: '式', reading: 'しき', en: 'ceremony', rank: 683 },
  { id: 'v684', jp: '楽しい', reading: 'たのしい', en: 'fun', rank: 684 },
  { id: 'v685', jp: '救う', reading: 'すくう', en: 'save', rank: 685 },
  { id: 'v686', jp: '局', reading: 'きょく', en: 'bureau', rank: 686 },
  { id: 'v687', jp: '残す', reading: 'のこす', en: 'leave', rank: 687 },
  { id: 'v688', jp: '地獄', reading: 'じごく', en: 'hell', rank: 688 },
  { id: 'v689', jp: 'トラック', reading: 'とらっく', en: 'truck', rank: 689 },
  { id: 'v690', jp: '高い', reading: 'たかい', en: 'high', rank: 690 },
  { id: 'v691', jp: '認める', reading: 'みとめる', en: 'admit', rank: 691 },
  { id: 'v692', jp: '似る', reading: 'にる', en: 'resemble', rank: 692 },
  { id: 'v693', jp: 'ひと', reading: 'ひと', en: 'person', rank: 693 },
  { id: 'v694', jp: '12', reading: 'じゅうに', en: 'twelve', rank: 694 },
  { id: 'v695', jp: '兵士', reading: 'へいし', en: 'soldier', rank: 695 },
  { id: 'v696', jp: '隠れる', reading: 'かくれる', en: 'hide', rank: 696 },
  { id: 'v697', jp: '赤ちゃん', reading: 'あかちゃん', en: 'baby', rank: 697 },
  { id: 'v698', jp: 'メッセージ', reading: 'めっせーじ', en: 'message', rank: 698 },
  { id: 'v699', jp: '立つ', reading: 'たつ', en: 'stand', rank: 699 },
  { id: 'v700', jp: '７', reading: 'なな', en: 'seven', rank: 700 },
  { id: 'v701', jp: 'ファイル', reading: 'ふぁいる', en: 'file', rank: 701 },
  { id: 'v702', jp: '選ぶ', reading: 'えらぶ', en: 'choose', rank: 702 },
  { id: 'v703', jp: 'サラ', reading: 'さら', en: 'Sarah', rank: 703 },
  { id: 'v704', jp: '止める', reading: 'とめる', en: 'stop', rank: 704 },
  { id: 'v705', jp: '山里', reading: 'やまさと', en: 'hamlet', rank: 705 },
  { id: 'v706', jp: '食事', reading: 'しょくじ', en: 'meal', rank: 706 },
  { id: 'v707', jp: '任せる', reading: 'まかせる', en: 'entrust', rank: 707 },
  { id: 'v708', jp: 'ちょうど', reading: 'ちょうど', en: 'exactly', rank: 708 },
  { id: 'v709', jp: '幸運', reading: 'こううん', en: 'good luck', rank: 709 },
  { id: 'v710', jp: '対する', reading: 'たいする', en: 'regarding', rank: 710 },
  { id: 'v711', jp: '侵入', reading: 'しんにゅう', en: 'invasion', rank: 711 },
  { id: 'v712', jp: '代わり', reading: 'かわり', en: 'instead', rank: 712 },
  { id: 'v713', jp: '親父', reading: 'おやじ', en: 'old man', rank: 713 },
  { id: 'v714', jp: '能力', reading: 'のうりょく', en: 'ability', rank: 714 },
  { id: 'v715', jp: '貸す', reading: 'かす', en: 'lend', rank: 715 },
  { id: 'v716', jp: '誘拐', reading: 'ゆうかい', en: 'kidnapping', rank: 716 },
  { id: 'v717', jp: '森', reading: 'もり', en: 'forest', rank: 717 },
  { id: 'v718', jp: '世話', reading: 'せわ', en: 'care', rank: 718 },
  { id: 'v719', jp: '9', reading: '９', en: 'nine', rank: 719 },
  { id: 'v720', jp: '階', reading: 'かい', en: 'floor', rank: 720 },
  { id: 'v721', jp: 'フランク', reading: 'フランク', en: 'Frank', rank: 721 },
  { id: 'v722', jp: 'イヤ', reading: 'いや', en: 'no', rank: 722 },
  { id: 'v723', jp: 'いま', reading: 'いま', en: 'now', rank: 723 },
  { id: 'v724', jp: '窓', reading: 'まど', en: 'window', rank: 724 },
  { id: 'v725', jp: '特に', reading: 'とくに', en: 'especially', rank: 725 },
  { id: 'v726', jp: '駄目', reading: 'だめ', en: 'no good', rank: 726 },
  { id: 'v727', jp: '耳', reading: 'みみ', en: 'ear', rank: 727 },
  { id: 'v728', jp: '緊急', reading: 'きんきゅう', en: 'emergency', rank: 728 },
  { id: 'v729', jp: '希望', reading: 'きぼう', en: 'hope', rank: 729 },
  { id: 'v730', jp: '怒る', reading: 'おこる', en: 'get angry', rank: 730 },
  { id: 'v731', jp: '傷つける', reading: 'きずつける', en: 'hurt', rank: 731 },
  { id: 'v732', jp: '狂う', reading: 'くるう', en: 'go mad', rank: 732 },
  { id: 'v733', jp: '火', reading: 'ひ', en: 'fire', rank: 733 },
  { id: 'v734', jp: '100', reading: 'ひゃく', en: 'one hundred', rank: 734 },
  { id: 'v735', jp: 'ロック', reading: 'ロック', en: 'rock music', rank: 735 },
  { id: 'v736', jp: '達也', reading: 'たつや', en: 'Tatsuya', rank: 736 },
  { id: 'v737', jp: '木', reading: 'き', en: 'tree', rank: 737 },
  { id: 'v738', jp: '酒', reading: 'さけ', en: 'sake', rank: 738 },
  { id: 'v739', jp: '原因', reading: 'げんいん', en: 'cause', rank: 739 },
  { id: 'v740', jp: '側', reading: 'がわ', en: 'side', rank: 740 },
  { id: 'v741', jp: '部下', reading: 'ぶか', en: 'subordinate', rank: 741 },
  { id: 'v742', jp: '思える', reading: 'おもえる', en: 'seem', rank: 742 },
  { id: 'v743', jp: '付ける', reading: 'つける', en: 'attach', rank: 743 },
  { id: 'v744', jp: 'テスト', reading: 'てすと', en: 'test', rank: 744 },
  { id: 'v745', jp: 'マイケル', reading: 'まいける', en: 'Michael', rank: 745 },
  { id: 'v746', jp: '追う', reading: 'おう', en: 'chase', rank: 746 },
  { id: 'v747', jp: '行為', reading: 'こうい', en: 'act', rank: 747 },
  { id: 'v748', jp: '馬', reading: 'うま', en: 'horse', rank: 748 },
  { id: 'v749', jp: '晩', reading: 'ばん', en: 'evening', rank: 749 },
  { id: 'v750', jp: '聞ける', reading: 'きける', en: 'can hear', rank: 750 },
  { id: 'v751', jp: 'おそらく', reading: 'おそらく', en: 'probably', rank: 751 },
  { id: 'v752', jp: '到着', reading: 'とうちゃく', en: 'arrival', rank: 752 },
  { id: 'v753', jp: '影響', reading: 'えいきょう', en: 'influence', rank: 753 },
  { id: 'v754', jp: '箱', reading: 'はこ', en: 'box', rank: 754 },
  { id: 'v755', jp: 'まぁ', reading: 'まあ', en: 'well', rank: 755 },
  { id: 'v756', jp: 'ミスター', reading: 'みすたー', en: 'mister', rank: 756 },
  { id: 'v757', jp: '遺体', reading: 'いたい', en: 'corpse', rank: 757 },
  { id: 'v758', jp: 'it', reading: 'いっと', en: 'it', rank: 758 },
  { id: 'v759', jp: '山', reading: 'やま', en: 'mountain', rank: 759 },
  { id: 'v760', jp: 'ウォルター', reading: 'うぉるたー', en: 'walter', rank: 760 },
  { id: 'v761', jp: 'みのり', reading: 'みのり', en: 'minori', rank: 761 },
  { id: 'v762', jp: '警告', reading: 'けいこく', en: 'warning', rank: 762 },
  { id: 'v763', jp: '感情', reading: 'かんじょう', en: 'emotion', rank: 763 },
  { id: 'v764', jp: '夕食', reading: 'ゆうしょく', en: 'dinner', rank: 764 },
  { id: 'v765', jp: '常', reading: 'つね', en: 'usual', rank: 765 },
  { id: 'v766', jp: 'ドイツ', reading: 'どいつ', en: 'germany', rank: 766 },
  { id: 'v767', jp: 't', reading: 'てぃー', en: 't', rank: 767 },
  { id: 'v768', jp: 'きれい', reading: 'きれい', en: 'pretty', rank: 768 },
  { id: 'v769', jp: '手紙', reading: 'てがみ', en: 'letter', rank: 769 },
  { id: 'v770', jp: 'スパイ', reading: 'すぱい', en: 'spy', rank: 770 },
  { id: 'v771', jp: '速', reading: 'そく', en: 'speed', rank: 771 },
  { id: 'v772', jp: '意見', reading: 'いけん', en: 'opinion', rank: 772 },
  { id: 'v773', jp: '支配', reading: 'しはい', en: 'domination', rank: 773 },
  { id: 'v774', jp: '要る', reading: 'いる', en: 'need', rank: 774 },
  { id: 'v775', jp: '戦う', reading: 'たたかう', en: 'fight', rank: 775 },
  { id: 'v776', jp: '島', reading: 'しま', en: 'island', rank: 776 },
  { id: 'v777', jp: '一部', reading: 'いちぶ', en: 'part', rank: 777 },
  { id: 'v778', jp: '知れる', reading: 'しれる', en: 'become known', rank: 778 },
  { id: 'v779', jp: '号', reading: 'ごう', en: 'number', rank: 779 },
  { id: 'v780', jp: '誕生', reading: 'たんじょう', en: 'birth', rank: 780 },
  { id: 'v781', jp: 'よろしく', reading: 'よろしく', en: 'best regards', rank: 781 },
  { id: 'v782', jp: 'チェック', reading: 'チェック', en: 'check', rank: 782 },
  { id: 'v783', jp: '光', reading: 'ひかり', en: 'light', rank: 783 },
  { id: 'v784', jp: '大切', reading: 'たいせつ', en: 'important', rank: 784 },
  { id: 'v785', jp: '少女', reading: 'しょうじょ', en: 'girl', rank: 785 },
  { id: 'v786', jp: '楽しむ', reading: 'たのしむ', en: 'enjoy', rank: 786 },
  { id: 'v787', jp: '半分', reading: 'はんぶん', en: 'half', rank: 787 },
  { id: 'v788', jp: '心臓', reading: 'しんぞう', en: 'heart', rank: 788 },
  { id: 'v789', jp: '魂', reading: 'たましい', en: 'soul', rank: 789 },
  { id: 'v790', jp: '自殺', reading: 'じさつ', en: 'suicide', rank: 790 },
  { id: 'v791', jp: '麻薬', reading: 'まやく', en: 'narcotics', rank: 791 },
  { id: 'v792', jp: '施設', reading: 'しせつ', en: 'institution', rank: 792 },
  { id: 'v793', jp: '機会', reading: 'きかい', en: 'opportunity', rank: 793 },
  { id: 'v794', jp: '現れる', reading: 'あらわれる', en: 'appear', rank: 794 },
  { id: 'v795', jp: '男性', reading: 'だんせい', en: 'male', rank: 795 },
  { id: 'v796', jp: 'いでる', reading: 'いでる', en: 'come out', rank: 796 },
  { id: 'v797', jp: '永遠', reading: 'えいえん', en: 'eternity', rank: 797 },
  { id: 'v798', jp: 'アレックス', reading: 'あれっくす', en: 'Alex', rank: 798 },
  { id: 'v799', jp: '海', reading: 'うみ', en: 'sea', rank: 799 },
  { id: 'v800', jp: '行方', reading: 'ゆくえ', en: 'whereabouts', rank: 800 },
  { id: 'v801', jp: '丿', reading: 'の', en: 'stroke', rank: 801 },
  { id: 'v802', jp: 'より', reading: 'より', en: 'than', rank: 802 },
  { id: 'v803', jp: '運命', reading: 'うんめい', en: 'fate', rank: 803 },
  { id: 'v804', jp: '料理', reading: 'りょうり', en: 'cooking', rank: 804 },
  { id: 'v805', jp: '左', reading: 'ひだり', en: 'left', rank: 805 },
  { id: 'v806', jp: 'いくら', reading: 'いくら', en: 'how much', rank: 806 },
  { id: 'v807', jp: '疲れる', reading: 'つかれる', en: 'get tired', rank: 807 },
  { id: 'v808', jp: '混乱', reading: 'こんらん', en: 'confusion', rank: 808 },
  { id: 'v809', jp: '部隊', reading: 'ぶたい', en: 'unit', rank: 809 },
  { id: 'v810', jp: 'オーケー', reading: 'おーけー', en: 'okay', rank: 810 },
  { id: 'v811', jp: 'トム', reading: 'とむ', en: 'Thom', rank: 811 },
  { id: 'v812', jp: '何者', reading: 'なにもの', en: 'who', rank: 812 },
  { id: 'v813', jp: '管理', reading: 'かんり', en: 'management', rank: 813 },
  { id: 'v814', jp: '活動', reading: 'かつどう', en: 'activity', rank: 814 },
  { id: 'v815', jp: 'ほんと', reading: 'ほんと', en: 'really', rank: 815 },
  { id: 'v816', jp: '着く', reading: 'つく', en: 'arrive', rank: 816 },
  { id: 'v817', jp: '反対', reading: 'はんたい', en: 'opposition', rank: 817 },
  { id: 'v818', jp: '女王', reading: 'じょおう', en: 'queen', rank: 818 },
  { id: 'v819', jp: '９', reading: '９', en: 'nine', rank: 819 },
  { id: 'v820', jp: '判断', reading: 'はんだん', en: 'judgment', rank: 820 },
  { id: 'v821', jp: '要求', reading: 'ようきゅう', en: 'request', rank: 821 },
  { id: 'v822', jp: 'チャーリー', reading: 'ちゃーりー', en: 'Charlie', rank: 822 },
  { id: 'v823', jp: '指示', reading: 'しじ', en: 'instruction', rank: 823 },
  { id: 'v824', jp: '生まれる', reading: 'うまれる', en: 'be born', rank: 824 },
  { id: 'v825', jp: '切る', reading: 'きる', en: 'cut', rank: 825 },
  { id: 'v826', jp: '面倒', reading: 'めんどう', en: 'trouble', rank: 826 },
  { id: 'v827', jp: 'マシン', reading: 'マシン', en: 'machine', rank: 827 },
  { id: 'v828', jp: '日本', reading: 'にほん', en: 'Japan', rank: 828 },
  { id: 'v829', jp: '色々', reading: 'いろいろ', en: 'various', rank: 829 },
  { id: 'v830', jp: '正確', reading: 'せいかく', en: 'accurate', rank: 830 },
  { id: 'v831', jp: 'おかげ', reading: 'おかげ', en: 'thanks', rank: 831 },
  { id: 'v832', jp: '分る', reading: 'わかる', en: 'understand', rank: 832 },
  { id: 'v833', jp: 'オフィス', reading: 'オフィス', en: 'office', rank: 833 },
  { id: 'v834', jp: '若い', reading: 'わかい', en: 'young', rank: 834 },
  { id: 'v835', jp: '右', reading: 'みぎ', en: 'right', rank: 835 },
  { id: 'v836', jp: '紹介', reading: 'しょうかい', en: 'introduction', rank: 836 },
  { id: 'v837', jp: '大好き', reading: 'だいすき', en: 'love', rank: 837 },
  { id: 'v838', jp: 'リー', reading: 'リー', en: 'Lee', rank: 838 },
  { id: 'v839', jp: '現在', reading: 'げんざい', en: 'present', rank: 839 },
  { id: 'v840', jp: '驚く', reading: 'おどろく', en: 'surprise', rank: 840 },
  { id: 'v841', jp: 'me', reading: 'みー', en: 'me', rank: 841 },
  { id: 'v842', jp: 'やっと', reading: 'やっと', en: 'finally', rank: 842 },
  { id: 'v843', jp: 'しばらく', reading: 'しばらく', en: 'awhile', rank: 843 },
  { id: 'v844', jp: 'コード', reading: 'コード', en: 'code', rank: 844 },
  { id: 'v845', jp: '映像', reading: 'えいぞう', en: 'image', rank: 845 },
  { id: 'v846', jp: 'やっぱり', reading: 'やっぱり', en: 'as expected', rank: 846 },
  { id: 'v847', jp: '出発', reading: 'しゅっぱつ', en: 'departure', rank: 847 },
  { id: 'v848', jp: '音楽', reading: 'おんがく', en: 'music', rank: 848 },
  { id: 'v849', jp: '空', reading: 'そら', en: 'sky', rank: 849 },
  { id: 'v850', jp: '反応', reading: 'はんのう', en: 'reaction', rank: 850 },
  { id: 'v851', jp: 'はっきり', reading: 'はっきり', en: 'clearly', rank: 851 },
  { id: 'v852', jp: '保安', reading: 'ほあん', en: 'security', rank: 852 },
  { id: 'v853', jp: '話せる', reading: 'はなせる', en: 'can speak', rank: 853 },
  { id: 'v854', jp: '議員', reading: 'ぎいん', en: 'legislator', rank: 854 },
  { id: 'v855', jp: '将軍', reading: 'しょうぐん', en: 'general', rank: 855 },
  { id: 'v856', jp: 'テレビ', reading: 'テレビ', en: 'television', rank: 856 },
  { id: 'v857', jp: '悪魔', reading: 'あくま', en: 'devil', rank: 857 },
  { id: 'v858', jp: '南', reading: 'みなみ', en: 'south', rank: 858 },
  { id: 'v859', jp: '担当', reading: 'たんとう', en: 'in charge', rank: 859 },
  { id: 'v860', jp: '市', reading: 'し', en: 'city', rank: 860 },
  { id: 'v861', jp: '開始', reading: 'かいし', en: 'start', rank: 861 },
  { id: 'v862', jp: '恐怖', reading: 'きょうふ', en: 'fear', rank: 862 },
];
